[platformio]
default_envs = native

[env:native]
platform = native
test_framework = unity
test_build_src = yes
build_src_filter = +<safety.cpp> +<operating_mode.cpp> -<main.cpp>
build_flags = -std=c++17

[env:waveshare_esp32s3]
platform = espressif32@6.10.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=1
    -DJARRED_DRIVE_HARDWARE=1
    -std=gnu++17
lib_deps =
    https://github.com/SolidGeek/VescUart.git#0f4fa9e1fc6996d51a8dbdcc9fabd488179bde4b
    adafruit/Adafruit ST7735 and ST7789 Library@1.11.0
    mikalhart/TinyGPSPlus@1.1.0
